name: Generate GitHub Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics - Light
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: lokeshgovindu
          template: classic
          base: header, activity, community, repositories, relevant
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8

      - name: Generate Metrics - Dark
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: lokeshgovindu
          template: classic
          base: header, activity, community, repositories, relevant
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          extras_css: |
            svg {
              filter: invert(1) hue-rotate(180deg);
            }
